const mongoose = require('mongoose');
require('dotenv').config();

const User = require('./models/User');
const Accommodation = require('./models/Accommodation');

const properties = [
  {
    title: 'Luxury Villa in Camps Bay',
    location: 'Cape Town',
    description: 'Stunning luxury villa overlooking the Atlantic Ocean in prestigious Camps Bay. Features a private infinity pool, modern open-plan living, and panoramic views of the Twelve Apostles mountain range. Walking distance to Camps Bay beach and trendy restaurants.',
    type: 'Entire villa',
    bedrooms: 4, bathrooms: 3, guests: 8, price: 4500,
    weeklyDiscount: 10, cleaningFee: 800, serviceFee: 450, occupancyTaxes: 200,
    amenities: ['pool', 'wifi', 'kitchen', 'free parking', 'air conditioning', 'tv', 'workspace'],
    rating: 4.9, reviews: 42,
    specificRatings: { cleanliness: 5, communication: 4.8, checkIn: 5, accuracy: 4.9, location: 5, value: 4.7 },
  },
  {
    title: 'Waterfront Apartment in Cape Town',
    location: 'Cape Town',
    description: 'Modern apartment in the heart of the V&A Waterfront. Enjoy stunning harbour views, world-class dining, and the vibrant atmosphere of Cape Town\'s most iconic destination. Secure building with 24-hour concierge.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 2800,
    weeklyDiscount: 8, cleaningFee: 500, serviceFee: 280, occupancyTaxes: 150,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'washer', 'tv'],
    rating: 4.8, reviews: 67,
    specificRatings: { cleanliness: 4.9, communication: 4.8, checkIn: 4.7, accuracy: 4.8, location: 5, value: 4.6 },
  },
  {
    title: 'Sandton Executive Apartment',
    location: 'Johannesburg',
    description: 'Premium executive apartment in the heart of Sandton, Africa\'s richest square mile. Walking distance to Sandton City Mall, Nelson Mandela Square, and Gautrain station. Perfect for business travellers.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 2200,
    weeklyDiscount: 7, cleaningFee: 400, serviceFee: 220, occupancyTaxes: 120,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'washer', 'tv', 'workspace', 'pool'],
    rating: 4.7, reviews: 89,
    specificRatings: { cleanliness: 4.8, communication: 4.7, checkIn: 4.8, accuracy: 4.6, location: 4.9, value: 4.5 },
  },
  {
    title: 'Durban Beachfront Penthouse',
    location: 'Durban',
    description: 'Spectacular penthouse apartment on Durban\'s famous Golden Mile. Floor-to-ceiling windows with uninterrupted Indian Ocean views. Direct beach access and close to uShaka Marine World.',
    type: 'Entire apartment',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 3200,
    weeklyDiscount: 10, cleaningFee: 600, serviceFee: 320, occupancyTaxes: 180,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'pool', 'tv', 'washer'],
    rating: 4.9, reviews: 55,
    specificRatings: { cleanliness: 4.9, communication: 4.8, checkIn: 4.9, accuracy: 4.8, location: 5, value: 4.7 },
  },
  {
    title: 'Stellenbosch Wine Estate Cottage',
    location: 'Stellenbosch',
    description: 'Charming cottage on a working wine estate in the heart of Stellenbosch. Surrounded by vineyards and mountain views. Enjoy wine tastings, cellar tours, and farm-to-table dining. A perfect weekend escape.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1800,
    weeklyDiscount: 12, cleaningFee: 350, serviceFee: 180, occupancyTaxes: 100,
    amenities: ['wifi', 'kitchen', 'free parking', 'heating', 'tv'],
    rating: 4.8, reviews: 73,
    specificRatings: { cleanliness: 4.7, communication: 4.9, checkIn: 4.8, accuracy: 4.8, location: 4.9, value: 4.8 },
  },
  {
    title: 'Knysna Lagoon House',
    location: 'Knysna',
    description: 'Beautiful house overlooking the famous Knysna Lagoon with the majestic Heads in the distance. Private jetty, braai area, and lush garden. Perfect for families and water sports enthusiasts.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 2500,
    weeklyDiscount: 10, cleaningFee: 500, serviceFee: 250, occupancyTaxes: 140,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv', 'workspace'],
    rating: 4.7, reviews: 38,
    specificRatings: { cleanliness: 4.6, communication: 4.7, checkIn: 4.7, accuracy: 4.6, location: 5, value: 4.6 },
  },
  {
    title: 'Hermanus Ocean View Villa',
    location: 'Hermanus',
    description: 'Luxury villa perched on the cliffs of Hermanus, the best land-based whale watching destination in the world. Watch Southern Right whales from your private deck. Fully equipped with modern amenities.',
    type: 'Entire villa',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 3500,
    weeklyDiscount: 10, cleaningFee: 600, serviceFee: 350, occupancyTaxes: 180,
    amenities: ['wifi', 'kitchen', 'free parking', 'heating', 'washer', 'tv', 'workspace'],
    rating: 4.9, reviews: 61,
    specificRatings: { cleanliness: 4.9, communication: 4.8, checkIn: 4.8, accuracy: 4.9, location: 5, value: 4.7 },
  },
  {
    title: 'Drakensberg Mountain Retreat',
    location: 'Drakensberg',
    description: 'Secluded mountain retreat in the heart of the Drakensberg. Spectacular views of the Amphitheatre. Features a cosy fireplace, hiking trails, and complete peace and quiet. No Wi-Fi — true digital detox.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1500,
    weeklyDiscount: 15, cleaningFee: 300, serviceFee: 150, occupancyTaxes: 80,
    amenities: ['kitchen', 'free parking', 'heating'],
    rating: 4.8, reviews: 44,
    specificRatings: { cleanliness: 4.7, communication: 4.6, checkIn: 4.5, accuracy: 4.8, location: 4.9, value: 4.9 },
  },
  {
    title: 'Ballito Coastal Apartment',
    location: 'Ballito',
    description: 'Modern beachfront apartment in Ballito on the Dolphin Coast. Direct beach access, communal pools, and close to the Ballito Junction shopping centre. Perfect family holiday destination.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 1800,
    weeklyDiscount: 8, cleaningFee: 350, serviceFee: 180, occupancyTaxes: 100,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'pool', 'tv', 'washer'],
    rating: 4.7, reviews: 52,
    specificRatings: { cleanliness: 4.7, communication: 4.7, checkIn: 4.6, accuracy: 4.7, location: 4.9, value: 4.6 },
  },
  {
    title: 'Pretoria Business Apartment',
    location: 'Pretoria',
    description: 'Conveniently located apartment in Pretoria\'s business district. Close to government buildings, Union Buildings, and Hatfield. Secure complex with backup power.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1200,
    weeklyDiscount: 5, cleaningFee: 250, serviceFee: 120, occupancyTaxes: 60,
    amenities: ['wifi', 'kitchen', 'free parking', 'workspace', 'tv'],
    rating: 4.5, reviews: 33,
    specificRatings: { cleanliness: 4.6, communication: 4.5, checkIn: 4.7, accuracy: 4.5, location: 4.8, value: 4.6 },
  },
  {
    title: 'Umhlanga Ridge Luxury Suite',
    location: 'Umhlanga',
    description: 'Luxurious suite in Umhlanga Ridge with panoramic ocean views. Walking distance to the iconic Umhlanga Lighthouse and Oyster Box Hotel. World-class dining and shopping nearby.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 2600,
    weeklyDiscount: 8, cleaningFee: 450, serviceFee: 260, occupancyTaxes: 140,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'pool', 'tv', 'washer', 'workspace'],
    rating: 4.8, reviews: 47,
    specificRatings: { cleanliness: 4.8, communication: 4.8, checkIn: 4.7, accuracy: 4.8, location: 5, value: 4.6 },
  },
  {
    title: 'Gqeberha Beach House',
    location: 'Gqeberha',
    description: 'Charming beach house in Gqeberha (Port Elizabeth) with direct access to stunning beaches. Close to Addo Elephant National Park for a complete Eastern Cape experience.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 2000,
    weeklyDiscount: 10, cleaningFee: 400, serviceFee: 200, occupancyTaxes: 110,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv'],
    rating: 4.6, reviews: 28,
    specificRatings: { cleanliness: 4.6, communication: 4.5, checkIn: 4.6, accuracy: 4.5, location: 4.8, value: 4.7 },
  },
  {
    title: 'Pilanesberg Safari Lodge',
    location: 'Pilanesberg',
    description: 'Experience the African bush from this luxury lodge in Pilanesberg Game Reserve. Game drives, bush walks, and stunning sunsets. All meals included. Close to Sun City resort.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 4000,
    weeklyDiscount: 10, cleaningFee: 0, serviceFee: 500, occupancyTaxes: 200,
    amenities: ['wifi', 'free parking', 'pool', 'tv'],
    rating: 4.9, reviews: 36,
    specificRatings: { cleanliness: 4.9, communication: 4.8, checkIn: 4.7, accuracy: 4.8, location: 5, value: 4.8 },
  },
  {
    title: 'Nelspruit Bushveld Cottage',
    location: 'Nelspruit',
    description: 'Self-catering cottage on the outskirts of Nelspruit, gateway to the Kruger National Park. Surrounded by indigenous bushveld with birdlife and wildlife. Perfect for nature lovers.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1400,
    weeklyDiscount: 10, cleaningFee: 300, serviceFee: 140, occupancyTaxes: 70,
    amenities: ['wifi', 'kitchen', 'free parking', 'tv'],
    rating: 4.6, reviews: 22,
    specificRatings: { cleanliness: 4.5, communication: 4.6, checkIn: 4.5, accuracy: 4.6, location: 4.7, value: 4.8 },
  },
  {
    title: 'Bloemfontein City Studio',
    location: 'Bloemfontein',
    description: 'Modern studio apartment in Bloemfontein city centre. Perfect for business travellers and students. Close to the University of the Free State and major hospitals.',
    type: 'Private room',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 650,
    weeklyDiscount: 5, cleaningFee: 150, serviceFee: 65, occupancyTaxes: 35,
    amenities: ['wifi', 'kitchen', 'free parking', 'workspace'],
    rating: 4.4, reviews: 19,
    specificRatings: { cleanliness: 4.5, communication: 4.4, checkIn: 4.6, accuracy: 4.4, location: 4.6, value: 4.7 },
  },
  {
    title: 'Mossel Bay Harbour View',
    location: 'Mossel Bay',
    description: 'Beautiful apartment overlooking Mossel Bay harbour. Close to the Dias Museum, Santos Beach, and the famous Cape St Blaize Cave. Great base for exploring the Garden Route.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1600,
    weeklyDiscount: 8, cleaningFee: 350, serviceFee: 160, occupancyTaxes: 90,
    amenities: ['wifi', 'kitchen', 'free parking', 'tv', 'washer'],
    rating: 4.7, reviews: 31,
    specificRatings: { cleanliness: 4.7, communication: 4.6, checkIn: 4.6, accuracy: 4.7, location: 4.9, value: 4.6 },
  },
  {
    title: 'George Golf Estate Home',
    location: 'George',
    description: 'Stunning home on the George Golf Estate with views of the Outeniqua Mountains. Access to the golf course, clubhouse, and tennis courts. Central Garden Route location.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 2200,
    weeklyDiscount: 10, cleaningFee: 450, serviceFee: 220, occupancyTaxes: 120,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv', 'workspace', 'pool'],
    rating: 4.7, reviews: 26,
    specificRatings: { cleanliness: 4.7, communication: 4.6, checkIn: 4.7, accuracy: 4.6, location: 4.8, value: 4.6 },
  },
  {
    title: 'Polokwane Game Farm Cabin',
    location: 'Polokwane',
    description: 'Rustic cabin on a private game farm near Polokwane. Enjoy game drives, bird watching, and starlit braais. A true Limpopo bushveld experience just minutes from the city.',
    type: 'Entire house',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1100,
    weeklyDiscount: 10, cleaningFee: 200, serviceFee: 110, occupancyTaxes: 60,
    amenities: ['kitchen', 'free parking'],
    rating: 4.5, reviews: 15,
    specificRatings: { cleanliness: 4.4, communication: 4.5, checkIn: 4.5, accuracy: 4.5, location: 4.6, value: 4.7 },
  },
  {
    title: 'Parkhurst Bohemian Cottage',
    location: 'Johannesburg',
    description: 'Charming cottage in trendy Parkhurst, Johannesburg. Walking distance to Fourth Avenue\'s famous restaurants and bars. Tree-lined streets and a tranquil garden setting.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 3, price: 1600,
    weeklyDiscount: 7, cleaningFee: 300, serviceFee: 160, occupancyTaxes: 85,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv'],
    rating: 4.8, reviews: 41,
    specificRatings: { cleanliness: 4.8, communication: 4.8, checkIn: 4.7, accuracy: 4.8, location: 4.9, value: 4.7 },
  },
  {
    title: 'Franschhoek Valley Manor',
    location: 'Stellenbosch',
    description: 'Grand manor house in the Franschhoek Valley, the gourmet capital of South Africa. Surrounded by vineyards and mountains. Walking distance to world-class restaurants and wine estates.',
    type: 'Entire villa',
    bedrooms: 5, bathrooms: 4, guests: 10, price: 6000,
    weeklyDiscount: 12, cleaningFee: 1000, serviceFee: 600, occupancyTaxes: 300,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'washer', 'tv', 'air conditioning'],
    rating: 4.9, reviews: 34,
    specificRatings: { cleanliness: 5, communication: 4.9, checkIn: 4.8, accuracy: 4.9, location: 5, value: 4.8 },
  },
  {
    title: 'Clifton Beach Penthouse',
    location: 'Cape Town',
    description: 'Ultra-luxurious penthouse overlooking Clifton\'s famous white sand beaches. Floor-to-ceiling glass, private rooftop terrace with jacuzzi, and direct access to the most exclusive beach in Cape Town.',
    type: 'Entire apartment',
    bedrooms: 3, bathrooms: 3, guests: 6, price: 5500,
    weeklyDiscount: 10, cleaningFee: 900, serviceFee: 550, occupancyTaxes: 280,
    amenities: ['wifi', 'kitchen', 'free parking', 'air conditioning', 'washer', 'tv', 'workspace'],
    rating: 5.0, reviews: 28,
    specificRatings: { cleanliness: 5, communication: 5, checkIn: 5, accuracy: 5, location: 5, value: 4.9 },
  },
  {
    title: 'Bokaap Heritage Townhouse',
    location: 'Cape Town',
    description: 'Beautifully restored Cape Malay townhouse in the colourful Bo-Kaap district. Cobblestone streets, spice-scented air, and views of Table Mountain from the rooftop terrace.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1800,
    weeklyDiscount: 8, cleaningFee: 350, serviceFee: 180, occupancyTaxes: 100,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer'],
    rating: 4.7, reviews: 35,
    specificRatings: { cleanliness: 4.6, communication: 4.7, checkIn: 4.5, accuracy: 4.7, location: 4.9, value: 4.8 },
  },
  {
    title: 'Constantia Vineyard Cottage',
    location: 'Cape Town',
    description: 'Tranquil cottage nestled in the Constantia Wine Valley. Surrounded by award-winning vineyards and mountain views. Private garden pool and outdoor braai area.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 3200,
    weeklyDiscount: 10, cleaningFee: 600, serviceFee: 320, occupancyTaxes: 180,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'workspace'],
    rating: 4.8, reviews: 51,
    specificRatings: { cleanliness: 4.7, communication: 4.8, checkIn: 4.6, accuracy: 4.8, location: 5, value: 4.6 },
  },
  {
    title: 'Muizenberg Surf Shack',
    location: 'Cape Town',
    description: 'Colourful beach cottage steps from Muizenberg\'s famous surfing beach. Retro decor, outdoor shower, and stunning sunset views over False Bay.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1400,
    weeklyDiscount: 7, cleaningFee: 250, serviceFee: 140, occupancyTaxes: 80,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer'],
    rating: 4.6, reviews: 68,
    specificRatings: { cleanliness: 4.5, communication: 4.6, checkIn: 4.4, accuracy: 4.6, location: 4.8, value: 4.9 },
  },
  {
    title: 'City Bowl Loft',
    location: 'Cape Town',
    description: 'Industrial-chic loft in the Cape Town City Bowl. Walking distance to Company Gardens, Long Street, and the Kloof Street restaurant strip. Rooftop pool and gym access.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1600,
    weeklyDiscount: 5, cleaningFee: 300, serviceFee: 160, occupancyTaxes: 90,
    amenities: ['wifi', 'kitchen', 'pool', 'workspace', 'air conditioning'],
    rating: 4.7, reviews: 43,
    specificRatings: { cleanliness: 4.6, communication: 4.7, checkIn: 4.8, accuracy: 4.6, location: 4.9, value: 4.7 },
  },
  {
    title: 'Morningside Boutique Suite',
    location: 'Johannesburg',
    description: 'Stylish suite in upmarket Morningside, Sandton. Close to Sandton City, freeway access, and the Gautrain station. Secure estate with 24-hour security and backup power.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1500,
    weeklyDiscount: 5, cleaningFee: 250, serviceFee: 150, occupancyTaxes: 80,
    amenities: ['wifi', 'kitchen', 'free parking', 'tv', 'workspace'],
    rating: 4.7, reviews: 29,
    specificRatings: { cleanliness: 4.7, communication: 4.6, checkIn: 4.5, accuracy: 4.7, location: 4.8, value: 4.6 },
  },
  {
    title: 'Melville Artsy Studio',
    location: 'Johannesburg',
    description: 'Eclectic studio in bohemian Melville. Surrounded by 7th Street\'s famous restaurants, bars, and live music venues. Perfect for creatives and nightlife enthusiasts.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 900,
    weeklyDiscount: 5, cleaningFee: 150, serviceFee: 90, occupancyTaxes: 50,
    amenities: ['wifi', 'kitchen', 'free parking'],
    rating: 4.5, reviews: 37,
    specificRatings: { cleanliness: 4.4, communication: 4.5, checkIn: 4.6, accuracy: 4.4, location: 4.8, value: 4.8 },
  },
  {
    title: 'Rosebank Luxury Apartment',
    location: 'Johannesburg',
    description: 'Modern high-rise apartment in the heart of Rosebank. Walking distance to the Rosebank Mall, Art Gallery, and Sunday market. Building has pool, gym, and concierge.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 2000,
    weeklyDiscount: 7, cleaningFee: 400, serviceFee: 200, occupancyTaxes: 120,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'workspace', 'air conditioning'],
    rating: 4.8, reviews: 45,
    specificRatings: { cleanliness: 4.8, communication: 4.7, checkIn: 4.8, accuracy: 4.7, location: 4.9, value: 4.6 },
  },
  {
    title: 'Fourways Family Home',
    location: 'Johannesburg',
    description: 'Spacious family home in secure Fourways estate. Large garden with pool, kids play area, and covered patio with braai. Close to Montecasino and Fourways Mall.',
    type: 'Entire house',
    bedrooms: 4, bathrooms: 2, guests: 8, price: 2800,
    weeklyDiscount: 10, cleaningFee: 500, serviceFee: 280, occupancyTaxes: 150,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'washer', 'tv', 'workspace'],
    rating: 4.6, reviews: 22,
    specificRatings: { cleanliness: 4.5, communication: 4.6, checkIn: 4.7, accuracy: 4.5, location: 4.6, value: 4.8 },
  },
  {
    title: 'Maboneng Urban Loft',
    location: 'Johannesburg',
    description: 'Trendy loft in the Maboneng Precinct, Joburg\'s cultural hub. Surrounded by street art, galleries, and hip cafes. Rooftop terrace with city skyline views.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1200,
    weeklyDiscount: 5, cleaningFee: 200, serviceFee: 120, occupancyTaxes: 70,
    amenities: ['wifi', 'kitchen', 'free parking', 'tv'],
    rating: 4.5, reviews: 31,
    specificRatings: { cleanliness: 4.4, communication: 4.5, checkIn: 4.6, accuracy: 4.4, location: 4.9, value: 4.7 },
  },
  {
    title: 'Umhlanga Rocks Beach Villa',
    location: 'Durban',
    description: 'Stunning beachfront villa in Umhlanga Rocks. Direct beach access, private pool, and panoramic ocean views. Walking distance to the Oyster Box and Umhlanga Lighthouse.',
    type: 'Entire villa',
    bedrooms: 4, bathrooms: 3, guests: 8, price: 4800,
    weeklyDiscount: 10, cleaningFee: 800, serviceFee: 480, occupancyTaxes: 250,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'washer', 'air conditioning'],
    rating: 4.9, reviews: 63,
    specificRatings: { cleanliness: 4.9, communication: 4.8, checkIn: 4.9, accuracy: 4.8, location: 5, value: 4.7 },
  },
  {
    title: 'Florida Road Garden Flat',
    location: 'Durban',
    description: 'Charming garden flat on Durban\'s famous Florida Road restaurant strip. Private entrance, leafy garden, and secure parking. Perfect for food lovers and urban explorers.',
    type: 'Entire apartment',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 1100,
    weeklyDiscount: 5, cleaningFee: 200, serviceFee: 110, occupancyTaxes: 60,
    amenities: ['wifi', 'kitchen', 'free parking', 'tv'],
    rating: 4.6, reviews: 27,
    specificRatings: { cleanliness: 4.5, communication: 4.6, checkIn: 4.7, accuracy: 4.5, location: 4.8, value: 4.7 },
  },
  {
    title: 'Musgrave Executive Apartment',
    location: 'Durban',
    description: 'Executive apartment in the prestigious Musgrave neighbourhood. Sweeping views of the Durban skyline and harbour. Secure building with pool and backup power.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 1900,
    weeklyDiscount: 8, cleaningFee: 350, serviceFee: 190, occupancyTaxes: 110,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'workspace'],
    rating: 4.7, reviews: 35,
    specificRatings: { cleanliness: 4.7, communication: 4.6, checkIn: 4.5, accuracy: 4.7, location: 4.8, value: 4.6 },
  },
  {
    title: 'Westville Country Retreat',
    location: 'Durban',
    description: 'Peaceful retreat in the leafy Durban suburb of Westville. Large garden with pool, outdoor braai area, and views of the Valley of 1000 Hills.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 2200,
    weeklyDiscount: 10, cleaningFee: 450, serviceFee: 220, occupancyTaxes: 130,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'washer', 'tv'],
    rating: 4.7, reviews: 19,
    specificRatings: { cleanliness: 4.6, communication: 4.7, checkIn: 4.5, accuracy: 4.6, location: 4.7, value: 4.8 },
  },
  {
    title: 'Ballito Beach House',
    location: 'Durban',
    description: 'Modern beach house in Ballito, just 30 minutes from Durban. Direct beach access, private garden, and stunning sea views. Perfect family getaway on the Dolphin Coast.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 6, price: 2500,
    weeklyDiscount: 10, cleaningFee: 500, serviceFee: 250, occupancyTaxes: 140,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv', 'air conditioning'],
    rating: 4.8, reviews: 44,
    specificRatings: { cleanliness: 4.7, communication: 4.8, checkIn: 4.6, accuracy: 4.8, location: 5, value: 4.7 },
  },
  {
    title: 'Midrand Golf Estate Home',
    location: 'Midrand',
    description: 'Beautiful family home on the Golf Estate in Midrand. Overlooking the fairway with a private pool, landscaped garden, and covered patio. Secure estate with clubhouse access.',
    type: 'Entire house',
    bedrooms: 4, bathrooms: 2, guests: 8, price: 2600,
    weeklyDiscount: 10, cleaningFee: 500, serviceFee: 260, occupancyTaxes: 140,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'washer', 'tv', 'workspace'],
    rating: 4.7, reviews: 24,
    specificRatings: { cleanliness: 4.6, communication: 4.7, checkIn: 4.5, accuracy: 4.7, location: 4.7, value: 4.6 },
  },
  {
    title: 'Carlswald Secure Townhouse',
    location: 'Midrand',
    description: 'Modern townhouse in the secure Carlswald Estate, Midrand. Open-plan living, private garden, and access to communal pool and tennis courts. Close to Mall of Africa.',
    type: 'Entire house',
    bedrooms: 3, bathrooms: 2, guests: 5, price: 1800,
    weeklyDiscount: 7, cleaningFee: 350, serviceFee: 180, occupancyTaxes: 100,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'washer'],
    rating: 4.5, reviews: 18,
    specificRatings: { cleanliness: 4.5, communication: 4.4, checkIn: 4.6, accuracy: 4.5, location: 4.6, value: 4.7 },
  },
  {
    title: 'Waterfall Executive Apartment',
    location: 'Midrand',
    description: 'Premium apartment in the prestigious Waterfall City development. Modern finishes, gym and pool access, and walking distance to the Mall of Africa and corporate offices.',
    type: 'Entire apartment',
    bedrooms: 2, bathrooms: 2, guests: 4, price: 2200,
    weeklyDiscount: 8, cleaningFee: 400, serviceFee: 220, occupancyTaxes: 120,
    amenities: ['wifi', 'kitchen', 'free parking', 'pool', 'tv', 'workspace', 'air conditioning'],
    rating: 4.8, reviews: 33,
    specificRatings: { cleanliness: 4.8, communication: 4.7, checkIn: 4.8, accuracy: 4.7, location: 4.9, value: 4.6 },
  },
  {
    title: 'Kyalami Country Cottage',
    location: 'Midrand',
    description: 'Charming cottage on a smallholding in Kyalami, Midrand. Horse stables, walking trails, and large garden. Peaceful country living just 20 minutes from Sandton.',
    type: 'Entire house',
    bedrooms: 2, bathrooms: 1, guests: 4, price: 1400,
    weeklyDiscount: 7, cleaningFee: 250, serviceFee: 140, occupancyTaxes: 80,
    amenities: ['wifi', 'kitchen', 'free parking', 'washer', 'tv'],
    rating: 4.6, reviews: 15,
    specificRatings: { cleanliness: 4.5, communication: 4.6, checkIn: 4.7, accuracy: 4.5, location: 4.7, value: 4.8 },
  },
  {
    title: 'Vorna Valley Modern Studio',
    location: 'Midrand',
    description: 'Contemporary studio apartment in Vorna Valley, Midrand. Perfect for business travellers. Close to the Gautrain station, Grand Central Airport, and major business hubs.',
    type: 'Private room',
    bedrooms: 1, bathrooms: 1, guests: 2, price: 750,
    weeklyDiscount: 5, cleaningFee: 150, serviceFee: 75, occupancyTaxes: 40,
    amenities: ['wifi', 'kitchen', 'free parking', 'workspace'],
    rating: 4.4, reviews: 21,
    specificRatings: { cleanliness: 4.4, communication: 4.5, checkIn: 4.6, accuracy: 4.4, location: 4.7, value: 4.7 },
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 30000 });
    console.log('MongoDB connected for seeding');

    // Remove existing accommodations to allow re-seeding
    await Accommodation.deleteMany({});
    console.log('Cleared existing properties');

    // Ensure a host user exists
    let host = await User.findOne({ role: 'host' });
    if (!host) {
      host = await User.create({
        username: 'Siyabonga',
        email: 'host@airbnb.co.za',
        password: 'host123456',
        role: 'host',
      });
      console.log('Created host user: host@airbnb.co.za / host123456');
    }

    // Create properties
    const withHost = properties.map((p) => ({
      ...p,
      host: host.username,
      host_id: host._id,
      images: [],
    }));

    const result = await Accommodation.insertMany(withHost);
    console.log(`Seeded ${result.length} South African properties successfully!`);

    await mongoose.disconnect();
    console.log('Done!');
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
